name: Generuj APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pobranie kodu źródłowego
      uses: actions/checkout@v4

    - name: Instalacja Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Instalacja Java (JDK 11)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Instalacja Apache Cordova
      run: npm install -g cordova

    - name: Przygotowanie struktury i budowanie
      run: |
        # Tworzymy tymczasowy folder www, którego wymaga Cordova w procesie budowania
        mkdir www
        # Kopiujemy luźne pliki z głównego katalogu do folderu www
        cp index.html www/
        cp icon.png www/
        # Instalacja platformy i kompilacja
        cordova platform add android
        cordova build android --packageType=apk --debug

    - name: Udostępnienie gotowego pliku APK
      uses: actions/upload-artifact@v4
      with:
        name: Nowa_Emerytura_APK
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
